#!/usr/bin/env python3
"""Independent reference generator for the SC-AUTH-v1 / SC-PAIR-v1 crypto contract.
Emits proto/auth-vectors.json — golden known-answer vectors every platform (Swift CryptoKit,
HarmonyOS cryptoFramework, Android javax.crypto) asserts at test time so cross-platform
HMAC / ECDH(P-256) / HKDF / AES-GCM interop is verifiable WITHOUT live devices.

ECDH curve is NIST P-256 (secp256r1) with x9.63 UNCOMPRESSED public keys (0x04||X||Y, 65 bytes):
uniformly available at each platform's min version (macOS 14 CryptoKit P256; HarmonyOS NEXT
cryptoFramework ECC; Android API 24+ JCA "ECDH" — X25519/"XDH" needs API 33+, too high for
minSdk 24). The shared secret is the 32-byte X coordinate; HKDF-SHA256 derives the AES key."""
import base64, hmac, hashlib, json, sys
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives.serialization import Encoding, PublicFormat
from cryptography.hazmat.primitives.kdf.hkdf import HKDF
from cryptography.hazmat.primitives.hashes import SHA256
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

def b64(b): return base64.b64encode(b).decode()
CURVE = ec.SECP256R1()

# ---- Fixed inputs (deterministic) ----
mac_peer  = "11111111-1111-4111-8111-111111111111"
tab_peer  = "22222222-2222-4222-8222-222222222222"
secret    = bytes(range(32))                          # 00..1f  (the long-lived per-pair secret)
nonce     = bytes((i*7)  & 0xff for i in range(32))   # tablet challenge (in hello_ack)
mac_nonce = bytes((i*11) & 0xff for i in range(32))   # Mac challenge (in auth)
# Fixed P-256 private scalars (big-endian, < curve order n). Both platforms init from these 32 bytes.
mac_eph_scalar = bytes(range(32))                     # 0x000102..1f
tab_eph_scalar = bytes(range(32, 64))                 # 0x2021..3f
salt       = bytes(range(16))
aead_nonce = bytes(range(12))

AUTH_LABEL = "SC-AUTH-v1"
PAIR_INFO  = b"SC-PAIR-v1"   # HKDF info + AES-GCM AAD

# ---- HMAC challenge-response (steady state) ----
# context is a pure UTF-8 string (easiest to reproduce byte-identically on every platform).
ctx_mac = (AUTH_LABEL + "|" + mac_peer + "|" + tab_peer + "|" + b64(nonce)).encode()
ctx_pad = (AUTH_LABEL + "|" + tab_peer + "|" + mac_peer + "|" + b64(mac_nonce)).encode()
proof_mac = hmac.new(secret, ctx_mac, hashlib.sha256).digest()   # Mac proves to Pad
proof_pad = hmac.new(secret, ctx_pad, hashlib.sha256).digest()   # Pad proves to Mac

# ---- P-256 ECDH (enrollment) ----
mac_sk = ec.derive_private_key(int.from_bytes(mac_eph_scalar, "big"), CURVE)
tab_sk = ec.derive_private_key(int.from_bytes(tab_eph_scalar, "big"), CURVE)
mac_pub = mac_sk.public_key().public_bytes(Encoding.X962, PublicFormat.UncompressedPoint)  # 65B 0x04||X||Y
tab_pub = tab_sk.public_key().public_bytes(Encoding.X962, PublicFormat.UncompressedPoint)
shared_m = mac_sk.exchange(ec.ECDH(), tab_sk.public_key())   # 32-byte X coordinate
shared_t = tab_sk.exchange(ec.ECDH(), mac_sk.public_key())
assert shared_m == shared_t, "ECDH must agree both directions"
shared = shared_m

ecdh_key = HKDF(algorithm=SHA256(), length=32, salt=salt, info=PAIR_INFO).derive(shared)
# enrollment: tablet seals `secret` under ecdh_key; Mac opens it.
enc = AESGCM(ecdh_key).encrypt(aead_nonce, secret, PAIR_INFO)   # ciphertext||tag (48B)
assert AESGCM(ecdh_key).decrypt(aead_nonce, enc, PAIR_INFO) == secret

vectors = {
  "_comment": "Golden KAT for SC-AUTH-v1 (HMAC challenge-response) + SC-PAIR-v1 (P-256 ECDH + HKDF-SHA256 + AES-256-GCM enrollment). Every platform asserts these at test time so cross-language crypto interop is build-verifiable without devices. ECDH = NIST P-256, public keys x9.63 uncompressed (0x04||X||Y, 65B); shared = 32-byte X coord. context = UTF-8 string; HMAC over its bytes. Generated by tools/gen-auth-vectors.py.",
  "authLabel": AUTH_LABEL,
  "pairInfo": "SC-PAIR-v1",
  "ecdhCurve": "P-256",
  "hmac": {
    "secretHex": secret.hex(),
    "macPeerId": mac_peer, "tabletPeerId": tab_peer,
    "nonceB64": b64(nonce), "macNonceB64": b64(mac_nonce),
    "contextMac": ctx_mac.decode(), "contextPad": ctx_pad.decode(),
    "proofMacB64": b64(proof_mac), "proofPadB64": b64(proof_pad)
  },
  "ecdh": {
    "curve": "P-256", "pubFormat": "x963-uncompressed-65B",
    "macEphScalarHex": mac_eph_scalar.hex(), "tabletEphScalarHex": tab_eph_scalar.hex(),
    "macEphPubB64": b64(mac_pub), "tabletEphPubB64": b64(tab_pub),
    "sharedHex": shared.hex(),
    "saltB64": b64(salt), "hkdfInfo": "SC-PAIR-v1", "ecdhKeyHex": ecdh_key.hex(),
    "aeadNonceB64": b64(aead_nonce), "aeadAad": "SC-PAIR-v1",
    "plaintextSecretHex": secret.hex(), "encSecretB64": b64(enc)
  }
}
out = sys.argv[1] if len(sys.argv) > 1 else "proto/auth-vectors.json"
with open(out, "w") as f:
    json.dump(vectors, f, indent=2)
    f.write("\n")
print("wrote", out)
print("curve P-256; proofMac", b64(proof_mac))
print("macEphPub(65B)", b64(mac_pub))
print("ecdhKey", ecdh_key.hex(), "encSecret", b64(enc), "len", len(enc))
